- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: java
  ansible.builtin.import_role:
    name: common
    tasks_from: java-setup

- name: mysql setup
  ansible.builtin.import_role:
    name: common
    tasks_from: mysql-setup

- name: system start
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd
# If you not using TEMPLATES, then keep the catalogue.service under files and give the shell module "ansible.builtin.shell"
