- name: "install {{component}}"
  hosts: "{{component}}"
  vars_files:
  - variables.yaml
  become: yes
  roles:
  - "{{component}}"

  #For keeping Place holders, we creating variable.yaml file and declared all HOST and calling through vars_files.