- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: Nodejs 18
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: MongoDB Setup
  ansible.builtin.import_role:
    name: common
    tasks_from: mongodb-setup

- name: systemctl status
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd