- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: GoLang
  ansible.builtin.import_role:
    name: common
    tasks_from: golang-setup

- name: systemctl status
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd

# If you not using TEMPLATES, then keep the catalogue.service under files and give the shell module "ansible.builtin.shell"
