- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: Nodejs 18
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: MongoDB Setup
  ansible.builtin.import_role:
    name: common
    tasks_from: mongodb-setup

- name: systemctl status
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd

- name: New Deployment Release
  ansible.builtin.import_role:
    name: common
    tasks_from: new-deployment

# If you not using TEMPLATES, then keep the catalogue.service under files and give the shell module "ansible.builtin.shell"
