- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: NodeJS-18
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: MongoDB
  ansible.builtin.import_role:
    name: common
    tasks_from: mongodb-setup