- name: disable old nodejs and enable nodejs
  ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

- name: Install nodejs
  ansible.builtin.dnf:
    name: nodejs 
    state: present

- name: Install dependencies (To change the working dir into /app dir)
  ansible.builtin.command: npm install
    args:
      chdir: /app