- name: Install GoLang
  ansible.builtin.dnf:
    name: golang
    state: present

- name: Build GoLang Application
  ansible.buitlin.command: "{{item}}"
  loop:
  - go mod init dispatch
  - go get
  - go build
  args:
    chdir: /app