- name: "Stop {{component}}" 
  tags:
  - deployment
  ansible.builtin.service:
    name: "{{component}}"
    state: stopped

- name: remove old code in /app directory
  tags:
  - deployment
  ansible.builtin.file:
    path: "app*"
    state: absent


#  -- Where it will use.?
# Ex: Consider the catalogue /roles/catalogue/tasks/main.yaml -> Suppose, you have new version to release, so we have to deployment the new version.
# while deploying--> do we need to RUN all these things (main.yaml) like  monggodb, appsetup, nodejs? --> NO.
# It is a OneTime Setup, once it is done, that's it.
	
# So, now the NEW deployment:  - what we will do is
#   Stop the Service.
#   remove old code
#   donwload latest code
#   restart the server.