- name: "stop {{component}}"
  tags:
  - deployment
  ansible.builtin.service:
    name: "{{component}}"
    state: stopped

- name: Recursively remove app directory
  tags:
  - deployment
  ansible.builtin.file:
    path: /app
    state: absent
    #force: yes
    #recurse: yes

- name: create app directory
  tags:
  - deployment
  ansible.builtin.file:
    path: /app
    state: directory

- name: "download {{component}} application"
  tags:
  - deployment
  ansible.builtin.get_url:
    url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
    dest: /tmp

- name: "extract {{component}} application"
  tags:
  - deployment
  ansible.builtin.unarchive:
    src: "/tmp/{{component}}.zip"
    dest: /app
    remote_src: yes

- name: Install dependencies
  tags:
  - deployment
  ansible.builtin.command: npm install
  args:
    chdir: /app

- name: "restart {{component}}"
  tags:
  - deployment
  ansible.builtin.service:
    name: "{{component}}"
    state: restarted

# Where it will use.?
# Ex: Consider the catalogue /roles/catalogue/tasks/main.yaml -> Suppose, you have new version to release, so we have to deployment the new version.
# while deploying--> do we need to RUN all these things (main.yaml) like  monggodb, appsetup, nodejs? --> NO.
# It is a OneTime Setup, once it is done, that's it.
# So, now the NEW deployment:  - what we will do is
#   Stop the Service.
#   remove old code
#   donwload latest code
#   restart the server.