# - name: "Copy {{component}} service"
#   ansible.builtin.copy:
#     src: "{{component}}.service"
#     dest: "/etc/systemd/system/{{component}}.service"

#If you are using TEMPLATES module stucture in Ansible
- name: "Copy {{component}} service"
  ansible.builtin.template:
    src: "{{component}}.service.j2"
    dest: "/etc/systemd/system/{{component}}.service"    

- name: deamon reload and start
  ansible.builtin.systemd_service:
    daemon_reload: true #Before starting, we are doing Daemon reload

- name: "start and enable the {{component}} module"
  ansible.builtin.service:
    name: "{{component}}"
    state: restarted
    enabled: yes